# Generated by Django 5.2.1 on 2025-06-04 10:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_bundle_created_at_bundle_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
