# Generated by Django 5.2.1 on 2025-06-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bundle_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Pro', 'Pro'), ('Special', 'Special')], default='Standard', max_length=20),
        ),
    ]
