# Generated by Django 5.2.1 on 2025-06-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as a featured item.'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_ready',
            field=models.BooleanField(default=False, help_text='Image has been generated and approved.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Hide product from public view (draft mode).'),
        ),
    ]
