# Generated by Django 5.2.1 on 2025-06-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_featured_product_image_ready_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbundle',
            options={'verbose_name': 'Bundle Product Link', 'verbose_name_plural': 'Included Products'},
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='product',
            field=models.ForeignKey(help_text='Select a product to include in this bundle.', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
