# Generated by Django 5.2.1 on 2025-06-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productbundle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
