# Generated by Django 5.2.1 on 2025-06-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_bundle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload the product image (optional).', null=True, upload_to='product_images/'),
        ),
    ]
