# Generated by Django 5.2.1 on 2025-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload the product image (optional).', max_length=255, null=True, upload_to='products/'),
        ),
    ]
