# Generated by Django 5.2.1 on 2025-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Discount percentage applied to the bundle.', max_digits=6),
        ),
    ]
