# Generated by Django 5.2.1 on 2025-06-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_bundle_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image directly.', max_length=255, null=True, upload_to='bundles/'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='image_path',
            field=models.CharField(blank=True, help_text='Optional: Provide relative S3 path (e.g. bundles/my-image.png)', max_length=255),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
