# Generated by Django 5.2.1 on 2025-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_bundle_image_bundle_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_code',
            field=models.CharField(default='TEMP_BUNDLE_CODE', help_text='Internal code used for SEO and tracking', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='sku',
            field=models.CharField(default='TEMP_SKU', help_text='Unique identifier for this bundle', max_length=50, unique=True),
        ),
    ]
