# Generated by Django 5.2.1 on 2025-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bundle_bundle_code_bundle_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
