# Generated by Django 5.2.1 on 2025-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_bundle_subtotal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='products.tag'),
        ),
    ]
