# Generated by Django 5.2.1 on 2025-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_bundle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
