# Generated by Django 5.2.1 on 2025-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City / Town'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='GB', help_text='Two-letter country code, e.g. GB, US.', max_length=2, verbose_name='Country (ISO-2)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_line1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_line2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Recipient name'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Contact phone'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Postcode'),
        ),
    ]
