# Generated by Django 5.2.1 on 2025-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_contact_email_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('requires_action', 'Requires Action')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_latest_event',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
