# Generated by Django 5.2.1 on 2025-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bundle_bundle_code_bundle_sku'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_bundles',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='products.bundle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='products.product'),
        ),
    ]
