# Generated by Django 5.2.1 on 2025-09-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('line1', models.CharField(blank=True, default='', max_length=255)),
                ('line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postcode', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='GB', max_length=2)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-id'),
                'indexes': [models.Index(fields=['user', 'is_default'], name='users_shipp_user_id_1e4f43_idx')],
            },
        ),
    ]
